/*
 * GENERATED by scripts/gen_keymap_glyphs.py -- do not edit by hand.
 * Regenerate after any change to config/klor.keymap.
 *
 * One character per key, laid out on the physical matrix grid, for each
 * layer. &trans is already resolved down the layer chain, so what is shown
 * is what the key actually does.
 */

#pragma once

#define KEYMAP_GLYPH_ROWS 4
#define KEYMAP_GLYPH_COLS 12
#define KEYMAP_GLYPH_LAYERS 4

/*
 * Which grid cells hold a key at all. Needed because a cell can be blank
 * yet still be a key -- Space is drawn as nothing -- and the renderer must
 * not mistake that for a hole in the board.
 */
static const char *const keymap_present[4] = {
    " xxxxxxxxxx ",
    "xxxxxxxxxxxx",
    "xxxxxxxxxxxx",
    " xxxxxxxxxx ",
};

/* [layer][row] -> one string of KEYMAP_GLYPH_COLS chars. */
static const char *const keymap_glyphs[4][4] = {
    { /* BASE */
        " QWERTYUIOP ",
        "eASDFGHJKL]<",
        "sZXCVBNM[;\\r",
        " cax mp,./' ",
    },
    { /* XTRA */
        " `~!@#1230+ ",
        "e$%^&_456-*<",
        "s()CVB789/=r",
        " caxgmp,f/' ",
    },
    { /* FN */
        " 23456789ab ",
        "1$%^&_456-*c",
        "s()CVB789/=r",
        " caxgmp,f/' ",
    },
    { /* SYS */
        " bbbbb***** ",
        "1bbbb_*****c",
        "soooR!!RP**r",
        " caxgmp,f/' ",
    },
};
