/*
 * GENERATED by scripts/gen_keymap_glyphs.py -- do not edit by hand.
 * Regenerate after any change to config/klor.keymap.
 *
 * One character per key, laid out on the physical matrix grid, for each
 * layer. &trans is already resolved down the layer chain, so what is shown
 * is what the key actually does.
 */

#pragma once

#define KEYMAP_GLYPH_ROWS 4
#define KEYMAP_GLYPH_COLS 12
#define KEYMAP_GLYPH_LAYERS 4

/* [layer][row] -> one string of KEYMAP_GLYPH_COLS chars, ' ' where no key. */
static const char *const keymap_glyphs[4][4] = {
    { /* BASE */
        " QWERTYUIOP ",
        "eASDFGHJKL]<",
        "sZXCVBNM[;\\r",
        " cax mp,./' ",
    },
    { /* XTRA */
        " `~!@#1230+ ",
        "e$%^&_456-*<",
        "s()CVB789/=r",
        " caxgmp,f/' ",
    },
    { /* FN */
        " 23456789ab ",
        "1          c",
        "s           ",
        " caxg   f   ",
    },
    { /* SYS */
        " bbbbb*     ",
        "1bbbb      c",
        "soooR!!RP   ",
        " caxg   f   ",
    },
};

#define KEYMAP_GLYPH_POSITIONS 44

/* Key position -> cell in the grid above. */
static const unsigned char keymap_pos_row[44] = {
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3
};
static const unsigned char keymap_pos_col[44] = {
    1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 5, 6, 6, 7, 8, 9, 10, 11, 1, 2, 3, 4, 7, 8, 9, 10
};
